server:
  port: 3001
spring:
  profiles:
    include:  db, redis, logging
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
