server:
  port: 3002
spring:
  profiles:
    include: db, redis, http, logging
  mvc:
    throw-exception-if-no-handler-found: true
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1